version: '3.6'

services:
#    db:
#        image: mongo
#        container_name: db
#        ports:
#            - '27017:27017'
#        volumes:
#            - ./data/mongo:/data/db
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
#        command: mongod
#        networks:
#            - app-network

    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile
#        links:
#            - db
        ports:
            - '4690:5001'
        volumes:
            - ./api/app:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
#        depends_on:
#            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
